<?php

namespace OperatorHub\Model;

use App\BookingEngine\Model\BookingConfiguration;
use OperatorHub\API\OperatorHubEngine;
use SilverStripe\Forms\FieldList;
use SilverStripe\Forms\PasswordField;
use SilverStripe\Forms\TextField;
use SilverStripe\Forms\ToggleCompositeField;

/**
 * @property string $User
 * @property string $Token
 * @property string $URL
 */
class OperatorHubBookingConfiguration extends BookingConfiguration
{
    private static $table_name = 'OperatorHub_OperatorHubBookingConfiguration';

    private static $singular_name = 'Operator Hub Config';

    private static $plural_name = 'Operator Hub Configs';

    private static $db = [
        'User'  => 'Varchar',
        'Token' => 'Varchar',
        'URL'   => 'Varchar',
    ];

    /**
     * Note: v3 API is 'https://api-beta.operatorhub.travel/api/webservice/v3'
     * @var array
     */
    private static $defaults = [
        'URL' => 'https://api-beta.junction6travel.com/jsonservice/v1/',
    ];

    public function getTitle()
    {
        return $this->getField('Title') ?: 'Operator Hub Config';
    }

    public function getBookingEngine()
    {
        return OperatorHubEngine::create()
            ->setConfiguration($this);
    }

    public function getCMSFields()
    {
        $this->beforeUpdateCMSFields(function (FieldList $fields) {
            $fields->addFieldsToTab('Root.Main', [
                ToggleCompositeField::create('OperatorHubFields', 'Operator Hub configuration', [
                    TextField::create('User', 'User name'),
                    PasswordField::create('Token', 'API Token')
                        ->setAllowValuePostback(true),
                    TextField::create('URL', 'API URL (v1)')
                ])
            ]);
        });

        return parent::getCMSFields(); // TODO: Change the autogenerated stub
    }
}
